#!/usr/bin/env bash
set -e

# Install Ansible
sudo apt update
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

# Run the playbook
sudo ansible-playbook ./full.yml