- hosts: localhost
  become: true
  vars_files:
    - config.yml
    
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  roles:
    - dev
    - network
    - system
    - toolbox
