---
- name: Create fonts directory
  file:
    path: "/home/{{ os_user }}/.fonts"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
  become_user: "{{ os_user }}"

- name: Install fonts file
  copy:
    src: .fonts/icomoon
    dest: "/home/{{ os_user }}/.fonts/"
    force: yes
    backup: yes
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: '0644'
