- name: Install arc theme
  apt: name=arc-theme

- name: Install python-psutil package
  apt: name=python-psutil

- name: Set GTK theme
  become_user: "{{ os_user }}"
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc-Dark'"
