galaxy_info:
  author: cyrillg
  description: shell tools setup
  license: MIT
  min_ansible_version: 2.9
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags: []
dependencies: []
  