---
- name: Download NodeJS 13 script
  get_url:
    url: https://deb.nodesource.com/setup_13.x
    dest: /tmp
    mode: 755

- name: Setup Node.js
  command: /tmp/setup_13.x

- name: Install NodeJS 13
  apt:
    name: [
      'nodejs',
      'gcc',
      'g++',
      'make']

- name: Add Yarn APT key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Install yarn
  apt:
    name: 'yarn'
