---
- name: Install debs (1/2)
  apt:
    name: [
      'curl',
      'htop',
      'powerline',
      'ranger',
      'screenfetch',
      'tree',
      'vifm',
      'wget',
      'xsel']

- name: Install debs (2/2)
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.13.0/bat-musl_0.13.0_amd64.deb
