---
- name: Install docker dependencies
  apt:
    name: [
      'apt-transport-https',
      'ca-certificates',
      'curl ',
      'gnupg-agent',
      'software-properties-common']

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Get distro name
  command: lsb_release -cs
  register: distro_name
  changed_when: False

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distro_name.stdout }} stable"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: False

- name: Install docker
  apt:
    name: [
      'docker-ce',
      'docker-ce-cli',
      'containerd.io']

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Adding user to docker group
  user:
    name: "{{ os_user }}"
    groups: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755

- name: Install docker-compose autocomplete
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/1.25.4/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: 755
